"use client"

import { useState } from "react"
import { Flame, AlertTriangle, Target, ShieldAlert, Check, X, Clock } from "lucide-react"
import { useMutation, useQueryClient } from "@tanstack/react-query"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { ViewSkeleton } from "./view-skeleton"
import { LeadQueueRow } from "./lead-queue-row"
import { useSuggestions, leadKeys } from "@/hooks/use-leads"
import { leadsApi } from "@/lib/api/leads"

function asOf(iso?: string | null): string {
  if (!iso) return ""
  const d = new Date(iso)
  return isNaN(d.getTime())
    ? ""
    : d.toLocaleString("en-IN", { day: "numeric", month: "short", hour: "numeric", minute: "2-digit" })
}

export function SuggestionsView({ onOpenLead }: { onOpenLead?: (id: string) => void }) {
  const { data: leads = [], isLoading } = useSuggestions()
  const qc = useQueryClient()
  const [busy, setBusy] = useState<string | null>(null)

  const mark = useMutation({
    mutationFn: ({ id, status }: { id: string; status: "acted" | "dismissed" }) =>
      leadsApi.markSuggestion(id, status),
    onMutate: (v) => setBusy(v.id),
    onSettled: () => {
      setBusy(null)
      qc.invalidateQueries({ queryKey: leadKeys.suggestions() })
      qc.invalidateQueries({ queryKey: leadKeys.queueCounts() })
    },
  })

  if (isLoading) return <ViewSkeleton />

  const runAt = leads[0]?.runAt

  return (
    <Card>
      <CardHeader className="pb-3">
        <div className="flex flex-wrap items-center justify-between gap-3">
          <div>
            <CardTitle className="text-base flex items-center gap-2">
              <Flame className="size-4 text-rose-500" />Close Today
            </CardTitle>
            <CardDescription>
              The daily shortlist of leads that look ready to close — with the reason and the
              exact push to make today, before the doctor buys elsewhere. Generated by the
              Close Today analysis when your laptop is on (about 6:00 AM and 2:00 PM).
            </CardDescription>
          </div>
          <div className="flex items-center gap-2">
            {runAt && (
              <span className="inline-flex items-center gap-1 text-[11px] text-muted-foreground">
                <Clock className="size-3" />as of {asOf(runAt)}
              </span>
            )}
            <Badge variant="outline" className="text-[10px]">{leads.length} to push</Badge>
          </div>
        </div>
      </CardHeader>
      <CardContent className="p-0">
        {leads.length === 0 ? (
          <p className="text-sm text-muted-foreground text-center py-10">
            No picks yet. The Close Today analysis will fill this list on its next run.
          </p>
        ) : (
          <div className="divide-y">
            {leads.map((lead) => (
              <LeadQueueRow
                key={lead.suggestionId}
                id={lead.id}
                name={lead.name}
                phone={lead.phone}
                equipment={lead.equipment}
                location={[lead.city, lead.state].filter((v) => v && v !== "—").join(", ") || undefined}
                replied={lead.replied}
                flagged={lead.flagged}
                urgent={lead.priority === "at_risk" ? { label: "At risk" } : undefined}
                onOpen={onOpenLead}
                meta={
                  <span className="flex flex-col gap-1">
                    {lead.whyCloseable && (
                      <span className="font-semibold text-emerald-700">{lead.whyCloseable}</span>
                    )}
                    <span className="flex flex-wrap items-center gap-1.5">
                      {lead.closingLever && (
                        <span className="inline-flex items-center gap-1 rounded bg-indigo-500/15 px-1.5 py-0.5 font-semibold text-indigo-700">
                          <Target className="size-3" />{lead.closingLever}
                        </span>
                      )}
                      {lead.riskIfDelayed && (
                        <span className="inline-flex items-center gap-1 rounded bg-amber-500/15 px-1.5 py-0.5 font-medium text-amber-700">
                          <ShieldAlert className="size-3" />{lead.riskIfDelayed}
                        </span>
                      )}
                    </span>
                    {lead.whyHot && <span className="text-muted-foreground">{lead.whyHot}</span>}
                    {lead.suggestedAction && (
                      <span className="text-muted-foreground">Today: {lead.suggestedAction}</span>
                    )}
                    {(lead.readiness != null || lead.urgency != null) && (
                      <span className="text-[11px] text-muted-foreground">
                        {lead.readiness != null && `Ready ${lead.readiness}/5`}
                        {lead.readiness != null && lead.urgency != null && " · "}
                        {lead.urgency != null && `Urgency ${lead.urgency}/5`}
                      </span>
                    )}
                  </span>
                }
                badge={
                  <span className="flex flex-col items-end gap-1">
                    {lead.priority === "at_risk" ? (
                      <Badge className="bg-amber-500 text-white text-[10px]">
                        <AlertTriangle className="size-3 mr-0.5" />At risk
                      </Badge>
                    ) : (
                      <Badge className="bg-rose-500 text-white text-[10px]">
                        <Flame className="size-3 mr-0.5" />Hot
                      </Badge>
                    )}
                    {lead.confidence && (
                      <span className="text-[10px] text-muted-foreground">{lead.confidence} confidence</span>
                    )}
                  </span>
                }
                actions={
                  <span className="flex items-center gap-1">
                    <Button
                      variant="ghost" size="sm" className="h-8 px-2.5"
                      onClick={() => onOpenLead?.(lead.id)}
                    >
                      Open
                    </Button>
                    <Button
                      variant="ghost" size="icon" className="h-8 w-8 text-emerald-600"
                      title="Mark worked" disabled={busy === lead.suggestionId}
                      onClick={() => mark.mutate({ id: lead.suggestionId, status: "acted" })}
                    >
                      <Check className="size-4" />
                    </Button>
                    <Button
                      variant="ghost" size="icon" className="h-8 w-8 text-muted-foreground"
                      title="Skip / not relevant" disabled={busy === lead.suggestionId}
                      onClick={() => mark.mutate({ id: lead.suggestionId, status: "dismissed" })}
                    >
                      <X className="size-4" />
                    </Button>
                  </span>
                }
              />
            ))}
          </div>
        )}
      </CardContent>
    </Card>
  )
}
